### ISSUE TITLE
PCB Designer 16.6

### ISSUE THREAD

**Issue by Kartohen** [juulsA/exportJson#2] opened 2023-04-24 04:33 UTC
![Issue](https://user-images.githubusercontent.com/131638318/233900239-fc26634c-30e0-481c-915e-49b7e3847a44.jpg)
Is this plugin supported for PCB Designer 16.6? It shows me an error for the board from example.

**Comment by juulsA** [comment] 2023-04-24 06:33
Unfortunetly this is a question I can't answer ... all programming and tests were done with 17.4. Based on the error I can guess, that the program is trying to access a value from an element that does not exist ... I try to add some debug messages to the code, so we can figure where this is happening ... thanks to cadence the line where the error occurs is not printed to the console ... but please give me some time for this.

**Comment by juulsA** [comment] 2023-04-24 06:36
another hint: all actions need to be completed / closed by clicking 'done', otherwise the skill scripts often do not run properly ... but I don't think, that this is the case here ...

**Comment by Kartohen** [comment] 2023-04-24 08:19
I've found the place where this error appears in the code:

![image](https://user-images.githubusercontent.com/131638318/233939357-8324565e-77cf-4af5-bcbe-a0000ebb53c3.png)

Changing var Extents helps to avoid error.

**Comment by juulsA** [comment] 2023-04-24 08:55
Thanks for your help! Maybe I have to add some lines of code, so that the script does not run into this error ... maybe the pcb editor 16.6 does not support the `dsn->designOutline` or the `axlDBGetExtents` call ... could you check what is the output of the `outline`, `segments` and `extents` by typing the following to the skill command line?

open the skill comand line ( `set teslkill` )

`dsn = axlDBGetDesign()`
`outline = dsn->designOutline`

outline should print somethings like this `dbid:000001B548763A30`

`segments = outline->segments`

should print a list of dbids

`extents = axlDBGetExtents( segments nil )`

prints two coordinates, if everything works as intended.

**Comment by Kartohen** [comment] 2023-04-24 09:03
On the next step I receive this error:

![image](https://user-images.githubusercontent.com/131638318/233950334-7ab42e67-cfaa-48d6-917d-6efcebc15da1.png)

**Comment by Kartohen** [comment] 2023-04-24 09:24
I have this result for Outline:

![image](https://user-images.githubusercontent.com/131638318/233956000-17751479-604d-4da4-a90e-a9eecd9e15f5.png)

**Comment by juulsA** [comment] 2023-04-24 09:56
okay... yeah, sorry, I forgot, that we don't have any information for the board outline now (dsn->boardOutline is nil) ... and edges is an unbound ... maybe we can check, if this is the only error we are running in. 

Please do the following: 

Comment out the addBoardGeometry in line 2178 (writeJsonFile) and execute exportJson

The function should complete, if there are no further "mistakes". If this works, we try to find a solution for our initial problem.

**Comment by juulsA** [comment] 2023-04-24 10:27
> After commenting export did complete. Would it be useful to attach .json file here?

No, I don't need the .json file, but now we know, that we just need to modify the `addBoardGeometry` function. 

Does this prints any dbids?

`segments = car( axlDBGetShapes( "Board Geometry/Design_Outline" ) )`

**Comment by Kartohen** [comment] 2023-04-24 10:29
![image](https://user-images.githubusercontent.com/131638318/233971090-e42dc6d6-3771-44ab-8c7e-4cc500c555cb.png)

**Comment by Kartohen** [comment] 2023-04-24 10:35
I set `extents =  margin` to prevent error about nil, if it matters.

**Comment by juulsA** [comment] 2023-04-24 10:39
> I set `extents = margin` to prevent error about nil, if it matters.

I don't think this is a problem. Can you find out, what's the name of the pcb contour layer and the cutouts? And then execute the previous command with the layer name?

**Comment by Kartohen** [comment] 2023-04-24 10:42
Outline:

`Skill > segments = car( axlDBGetShapes( "Board Geometry/Outline" ) )
dbid:376073928
Skill > `

**Comment by juulsA** [comment] 2023-04-24 11:00
Then you don't need the lines 686 - 688:

Can be removed:
`dsn = axlDBGetDesign()`
`outline = dsn->designOutline`
`segments = outline->segments`

and replaced by:
`segments = car( axlDBGetShapes( "Board Geometry/Outline" ) )`

Maybe you can try, if `extents =  axlDBGetExtents( segments nil )` is working now, otherwise leave it as you modified it.

Uncomment the previously commented line [addBoardGeometry](https://github.com/juulsA/exportJson/blob/c037f93d9abe31ce593c06817c29709fb07750a9/exportJson.il#L2178) and give the exportJson a new try.

**Comment by Kartohen** [comment] 2023-04-24 11:11
Now I get this kind of error:
`E- *Error* foreach: second argument must be a list - dbid:177495752`

Maybe the issue is in Cutout layer? I can't find it, the only similar layer name is Cut_marks. But for this layer I have:

`Skill > segments = car( axlDBGetShapes( "Board Geometry/Cut_Marks" ) )`
`nil`

**Comment by juulsA** [comment] 2023-04-24 11:33
To get this running without the cutout layer (comment line 726 - 739).

Does this error returns from the call `axlDBGetExtents ( ... )`? Then please modify it the way you have done it before.

**Comment by Kartohen** [comment] 2023-04-24 11:47
All variants give the same result:
`E- *Error* foreach: second argument must be a list - dbid:177495752`

Only if I comment lines 707-750, export can complete.

**Comment by juulsA** [comment] 2023-04-24 12:02
My mistake ... 
it should be:

`outline = car( axlDBGetShapes( "Board Geometry/Outline" ) )`
`segments = outline->segments`

instead of only 

`segments = car( axlDBGetShapes( "Board Geometry/Outline" ) )`

Please try this.

**Comment by juulsA** [comment] 2023-04-24 12:39
Ok, great! I'll check, if I can solve the issue with a few lines of code, so that the script is also working for older versions of allegro.
Thank you for reporting this issue ;)

**Comment by Kartohen** [comment] 2023-04-25 03:41
The latest version works properly with ver. 16.6! Thank you!

**Comment by Kartohen** [comment] 2023-04-25 08:41
I found out, that in HTML all elements are located on Back side and Front side is empty. File from the example works correct, and file .json that was made in ver. 16.6 has this error.

**Comment by juulsA** [comment] 2023-04-25 09:12
Can you share the .json file?

**Comment by Kartohen** [comment] 2023-04-25 09:13
[My.txt](https://github.com/juulsA/exportJson/files/11320817/My.txt)

**Comment by Kartohen** [comment] 2023-04-25 09:14
As I understand, in this line, for example, should be `"layer": "F"`?

**Comment by juulsA** [comment] 2023-04-25 09:25
Yes, if I run the script on this project the layer is set to `"F"`. 

Can you add the following to line 1381:

`print( symbol->layer )`

And tell me what is the output? Thanks!

**Comment by Kartohen** [comment] 2023-04-25 09:38
Result is the same, Front is empty

[AD-FMComms3.txt](https://github.com/juulsA/exportJson/files/11321076/AD-FMComms3.txt)

**Comment by juulsA** [comment] 2023-04-25 09:40
> Result is the same, Front is empty
> 
> [AD-FMComms3.txt](https://github.com/juulsA/exportJson/files/11321076/AD-FMComms3.txt)

The command should have printed something to your command line. 

But I think I have to change the code there ... please have some patience

**Comment by Kartohen** [comment] 2023-04-25 09:47
I added line `print( symbol->layer )` to file exportJson, is it my mistake? 
Should I add it to file .json?

**Comment by juulsA** [comment] 2023-04-25 09:58
No, to the `exportJson.il`. But please check my latest commit, I hope, I fixed it.

**Comment by Kartohen** [comment] 2023-04-25 10:15
And do you have an opportunity to open my .json file in iBOM? Maybe mistake is only on my side?

**Comment by Kartohen** [comment] 2023-04-25 10:39
In .json we need here and for the same elements `"F"`:

![image](https://user-images.githubusercontent.com/131638318/234252407-88edf338-8f13-4de1-ad6b-6e84e3aefd46.png)

This way iBom would work correct.

**Comment by juulsA** [comment] 2023-04-25 10:52
Yes, this is what I just saw ... But please do this as I described above and make your command line visible, because the information I need is only printed to the command line. And tell me the results.

> Yes, if I run the script on this project the layer is set to `"F"`.
> 
> Can you add the following to line 1381:
> 
> `print( symbol->layer )`
> 
> And tell me what is the output? Thanks!

**Comment by juulsA** [comment] 2023-04-25 11:02
Ok, give me some time to make some changes to the code.

**Comment by juulsA** [comment] 2023-04-25 13:02
Please update to the latest version and give it another try ... hopefully it works now!

**Comment by Kartohen** [comment] 2023-04-25 14:41
Now everything is alright! Thank You!

**Closed** 2023-04-26 06:09 UTC
